### ISSUE TITLE
Default Config: Add Apple drops for Oak and Dark Oak saplings.

### ISSUE THREAD

**Issue by MitchDizzle** [MitchDizzle/PaperBonsaiTrees#3]
Mentioned here:
https://minecraft.gamepedia.com/Apple#Trees

Apples drop from oak and dark oak leaves. Leaves have a 0.5% chance to drop apples, meaning Oak Trees have a 25% chance to drop an apple and Dark Oak trees have a 60% chance to drop an apple.
Since this chance system acts differently since it only drops one item per successful growth I think changing the config like this: (reducing amount of sticks produced in half)
```yaml
dropMap:
  POTTED_OAK_SAPLING:
    STICK: 0.1
    APPLE: 0.1
    OAK_LOG: 0.5
    OAK_LEAVES: 0.1
    OAK_SAPLING: 0.1
  POTTED_DARK_OAK_SAPLING:
    STICK: 0.1
    APPLE: 0.1
    DARK_OAK_LOG: 0.6
    DARK_OAK_LEAVES: 0.1
    DARK_OAK_SAPLING: 0.1
```
And perhaps reducing the amount of sticks produced by the rest of the saplings also (except dead_bush).
