### ISSUE TITLE
Ability to configure dropMap key per basis

### ISSUE THREAD

**Issue by MitchDizzle** [MitchDizzle/PaperBonsaiTrees#4]
Perhaps you want a certain potted sapling/plant to grow slower (or faster). Instead of changing the global percentages etc.
This would also include the other properties and percentages:
```yaml
# growth max percent per second
growthMaxPerSecond: 20.0
# growth min percent per second
growthMinPerSecond: 10.0
# growth percent when a player uses bonemeal on the pot.
bonemealIncreasePercent: 100.0
```
